#!/usr/bin/env bash 
# Создаем юзера
useradd -r -s /bin/false node_exporter
# Скачиваем, распаковываем
wget 
tar -xvf node_exporter-1.9.1.linux-amd64.tar.gz
# Копируем в директорию к бинарникам
sudo cp node_exporter-*/node_exporter /usr/local/bin/

sudo chown node_exporter:node_exporter /usr/local/bin/node_exporter

# Создаем демона
sudo nano /etc/systemd/system/node_exporter.service

[Unit]
Description=Node Exporter
Wants=network-online.target
After=network-online.target

[Service]
User=node_exporter
Group=node_exporter
ExecStart=/usr/local/bin/node_exporter
Restart=always

[Install]
WantedBy=multi-user.target

# Запускаем
sudo systemctl daemon-reload
sudo systemctl enable --now node_exporter
sudo systemctl status node_exporter
